// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNUCF4L7mbZOmbwfgu5CIXAYs3jVtV8sk',
    appId: '1:352736844640:web:c046b91bbd62dce2dcdc05',
    messagingSenderId: '352736844640',
    projectId: 'safarsync-f272c',
    authDomain: 'safarsync-f272c.firebaseapp.com',
    storageBucket: 'safarsync-f272c.firebasestorage.app',
    measurementId: 'G-QCBDXWTR9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mIM1cdkE4qeQ9kMaD1JnR9y25yihU1M',
    appId: '1:352736844640:android:0297c95c6dba337bdcdc05',
    messagingSenderId: '352736844640',
    projectId: 'safarsync-f272c',
    storageBucket: 'safarsync-f272c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpMGMzHVtdBjBRen-NXhitQSO6aCKPEDk',
    appId: '1:352736844640:ios:cc32c4cbc65c5155dcdc05',
    messagingSenderId: '352736844640',
    projectId: 'safarsync-f272c',
    storageBucket: 'safarsync-f272c.firebasestorage.app',
    iosBundleId: 'com.example.safarsyncMobileapp',
  );
}
