// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlQ4IoWDs7sY0YrkR4Ert0PIlwIZgUO9k',
    appId: '1:176464109317:web:a306a568efe403e658616c',
    messagingSenderId: '176464109317',
    projectId: 'safarsync-273c5',
    authDomain: 'safarsync-273c5.firebaseapp.com',
    storageBucket: 'safarsync-273c5.firebasestorage.app',
    measurementId: 'G-QQWKZNLB05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJPimJVyxPMnZcCfUAXYL9zfJVgK6-aOU',
    appId: '1:176464109317:android:7a88d78d2b8794c558616c',
    messagingSenderId: '176464109317',
    projectId: 'safarsync-273c5',
    storageBucket: 'safarsync-273c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpMGMzHVtdBjBRen-NXhitQSO6aCKPEDk',
    appId: '1:352736844640:ios:cc32c4cbc65c5155dcdc05',
    messagingSenderId: '352736844640',
    projectId: 'safarsync-f272c',
    storageBucket: 'safarsync-f272c.firebasestorage.app',
    iosBundleId: 'com.example.safarsyncMobileapp',
  );
}